<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.tcket</groupId>
        <artifactId>couchbase-dcp-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>couchbase-dcp-boot</artifactId>
    <name>Couchbase DCP Boot</name>
    <description>Boot module to start entire application</description>

    <dependencies>
        <dependency>
            <groupId>com.tcket</groupId>
            <artifactId>couchbase-dcp-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.tcket</groupId>
            <artifactId>couchbase-dcp-reader</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.tcket</groupId>
            <artifactId>couchbase-dcp-kafka</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>