spring:
  application:
    name: couchbase-dcp-boot
  couchbase:
    connection-string: couchbase://127.0.0.1
    username: Administrator
    password: Administrator

server:
  port: 8081

kafka:
  bootstrap-servers: pkc-921jm.us-east-2.aws.confluent.cloud:9092
  username: PKFS7CSZAK6526IA
  password: cflt2wWAcEKfsRyaw4xiCGG7odo8yUZ6t5t2l/2HpZk12s4vwJWpvvTfoVR/5N/g